# Generated by Django 4.0.10 on 2024-05-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='balance',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
