# Generated by Django 4.0.10 on 2024-05-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_page', '0004_kupon_match_kupon_kazanc'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
